const nodemailer = require('nodemailer');

// Email configuration
const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
        user: process.env.GMAIL_USER,
        pass: process.env.GMAIL_PASS
    }
});

// Email template function
function createEmailTemplate(reportData) {
    const formatTimeForEmail = (timeString) => {
        const [hours, minutes] = timeString.split(':');
        const hour = parseInt(hours);
        const period = hour >= 12 ? 'PM' : 'AM';
        const displayHour = hour % 12 || 12;
        return `${displayHour} ${period}`;
    };

    return `
        <!DOCTYPE html>
        <html>
        <head>
            <style>
                body { font-family: Arial, sans-serif; color: #333; line-height: 1.6; }
                .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; color: white; text-align: center; }
                .content { padding: 25px; background: #ffffff; }
                .summary { background: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0; }
                .goal-list { list-style: none; padding: 0; }
                .goal-item { padding: 12px 0; border-bottom: 1px solid #eee; }
                .completed { color: #27ae60; }
                .pending { color: #e74c3c; }
                .footer { text-align: center; padding: 20px; color: #7f8c8d; font-size: 12px; }
            </style>
        </head>
        <body>
            <div class="header">
                <h1>💧 Hydration Report Submitted!</h1>
                <p>Your daily water intake tracking data has been recorded</p>
            </div>
            
            <div class="content">
                <div class="summary">
                    <h2>📊 Submission Summary</h2>
                    <p><strong>Date:</strong> ${reportData.date}</p>
                    <p><strong>Time:</strong> ${reportData.time}</p>
                    <p><strong>Location:</strong> ${reportData.location.city}, ${reportData.location.region}</p>
                    <p><strong>Completion:</strong> ${reportData.totalCompleted} of ${reportData.totalGoals} goals (${Math.round(reportData.percentage)}%)</p>
                </div>

                <h3>💧 Goal Status:</h3>
                <ul class="goal-list">
                    ${reportData.goals.map(goal => `
                        <li class="goal-item">
                            <strong>${formatTimeForEmail(goal.time)}:</strong> ${goal.label} - 
                            <span class="${goal.completed ? 'completed' : 'pending'}">
                                ${goal.completed ? '✅ Completed' : '⏳ ' + goal.status}
                            </span>
                        </li>
                    `).join('')}
                </ul>
            </div>
            
            <div class="footer">
                <p>This email was automatically generated by HydraTrac System</p>
            </div>
        </body>
        </html>
    `;
}

module.exports = async (req, res) => {
    // Enhanced CORS headers
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
    
    // Handle preflight requests
    if (req.method === 'OPTIONS') {
        return res.status(200).end();
    }
    
    if (req.method === 'POST') {
        try {
            console.log('Received request to send report');
            
            // Parse JSON body
            let reportData;
            try {
                reportData = typeof req.body === 'string' ? JSON.parse(req.body) : req.body;
            } catch (parseError) {
                return res.status(400).json({
                    success: false,
                    message: 'Invalid JSON format'
                });
            }
            
            console.log('Report data:', reportData);

            // Validate required fields
            if (!reportData || !reportData.goals) {
                return res.status(400).json({
                    success: false,
                    message: 'Missing required data'
                });
            }

            // Email options
            const mailOptions = {
                from: '"HydraTrac System" <hydratrac@gmail.com>',
                to: 'shashinrajkumar@gmail.com',
                subject: `💧 Hydration Report - ${reportData.date} - ${Math.round(reportData.percentage)}% Complete`,
                html: createEmailTemplate(reportData)
            };

            // Send email
            await transporter.sendMail(mailOptions);
            
            console.log('Email sent successfully');
            res.status(200).json({ 
                success: true, 
                message: 'Report submitted and email sent successfully'
            });
            
        } catch (error) {
            console.error('Error sending email:', error);
            res.status(500).json({ 
                success: false,     
                message: 'Failed to send email: ' + error.message
            });
        }
    } else {
        res.status(405).json({ message: 'Method not allowed. Use POST.' });
    }
};